### ISSUE TITLE
No valid DB Connection Given

### ISSUE THREAD

**Issue by llawwehttam** [porowns/pathfinder-docker#15]
Hi.

I've just spun up an instance following the instructions.
However, on navigating to the /setup/ I get the error: "No valid DB Connection Given"

I can see in the pathfinder container that the name set for the database host is db.
However, in my instance it appears to be named pathfinder_db_1.
Unfortunately changing this doesn't appear to have made any difference.

Any ideas?

**Comment by llawwehttam** [comment]
Found the issue - by default the "pathfinder" database does not appear to be created within the mysql docker container.
Is that something that can be automated?

**Comment by porowns** [comment]
You need to spin up a MySQL container on the same docker network, or adjust your host/etc. 

You should use our docker compose file (it includes a mysql container), read the instructions in the README :)

**Comment by november781** [comment]
On the note @porowns made, I was working with a person that was having the same issue. Check your firewall rules (not sure if that will help) and try now with the new image. We got his working after the second try
