### ISSUE TITLE
Importing Maps - Max_input_vars?

### ISSUE THREAD

**Issue by GQuantrill** [porowns/pathfinder-docker#16]
Hello,
First up, love your work.  Really nicely down.

I'm struggling and I think I'm missing something. 
Basically, I'm attempting to import a map which is fairly large (It's all of Catch). 

I hit the issue whereby php states "{"status":"Internal Server Error","code":500,"text":"Fatal error: Unknown: Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini.","level":0}"

In the config/php.ini I've increased the value to say 5000 but it doesn't appear to take any notice of this.

Am I missing something?

**Comment by GQuantrill** [comment]
Managed to get around this.  I'd not noticed the ./config/php.ini wasn't actually being used.

Managed to get around this issue but noticed that the entries for max_corp_systems isn't being set either so I'll fiddle around.

**Comment by november781** [comment]
@GQuantrill the max_corp_systems is managed on the browser side, its getting set but the browser is not letting you access the new limit. That is an issue with the pathfinder project itself.

and as for your input vars, the /config/* files are only used when building a new image, be default the image is getting pulled from docker and will not represent any changes you made to those files.

The only values that change without building a new image are the ones in the .env file

**Comment by GQuantrill** [comment]
@november781 Thanks.  It's not a browser issue by the look of things.  The pathfinder.ini in 'var/www/pathfinder/conf/' is never generated (nor is the folder) therefore it doesn't take any of the .env file where those settings are being written.  I'm not sure why as the entrypoint.sh indicates it should be.

I've got around it by literally creating and copying over a new file into that location.

**Comment by november781** [comment]
would you mind helping me troubleshoot this on your end? that stuff was part of my commit line and if it is broken, I would like to get it fixed

Not to mention, this is the first time I'm seeing this

**Comment by GQuantrill** [comment]
@november781 Yes, not a problem.  I've forked the repo so I can play around a little and see what's amiss.

I'll ignore the php issue for now as that's likely to just me.  I'm trying to import 109 systems in a single map so I suspect that's edge case!

**Comment by november781** [comment]
out of curiosity, what OS/server are you building on?

**Comment by GQuantrill** [comment]
I've tried it on 2 OS's so far.

Ubuntu 18.04
OSX Mojave (10.14.6)

**Comment by november781** [comment]
hmm, my Ubuntu server (what I have this deployed on) works fine, I know @porowns uses (or has used mac) and it works fine on windows for me.

EDIT: no longer works on windows.

would you please re-open the issue while we work on it?

**Comment by november781** [comment]
@GQuantrill try changing your image in docker-compose.yml from `kryptedgaming/pathfinder:latest` to `kryptedgaming/pathfinder:lastest` looks like there was a typo in tagging the latest image

**Comment by GQuantrill** [comment]
@november781 Just changed and it works perfectly now!  Thank you.

**Comment by porowns** [comment]
Sorry about that. New naming schema:
```
lastest build
lastest-lastest build
most-lastest build
```

Just kidding... latest image is pushing now, I'm going to delete my fat-finger mistake.

**Comment by GQuantrill** [comment]
hehe, happens to everyone :)  I kinda like the naming convention :D

**Comment by porowns** [comment]
I'd recommend also joining our support discord: https://discord.gg/Nd3RYZ
