### ISSUE TITLE
AddAdminChar

### ISSUE THREAD

**Issue by llawwehttam** [porowns/pathfinder-docker#18]
From what I can tell, AddAdminChar and AdminCharID do not appear to be added to the pathfinder config.

Assuming the entrypoint.sh script in the repo is up to date I would have expected these values to end up in /var/www/pathfinder/conf/pathfinder.ini.

However, the conf directory doesn't appear to exist and while the majority of the settings in .env make it into the actual configuration file /var/www/pathfinder/app/pathfinder.ini the AddAdminChar and AdminCharID do not.

**Comment by llawwehttam** [comment]
Just checked and the entrypoint.sh script in the image differs from the one in this repo.

I'm rebuilding the image for myself.

I'm kinda new to Docker so I assume there is a reason the image differs from this repo?

**Comment by porowns** [comment]
Hm, shouldn't differ. Might need to publish a new image.
