### ISSUE TITLE
Cannot create needed DB. Unknown MYSQL root pw.

### ISSUE THREAD

**Issue by Valiantiam** [porowns/pathfinder-docker#19]
Per the instructions, it asks you to go into the shell for the container running mysql. I do so, but it didnt use my .env variable for the password, because its not working.

I deleted my containers and re-composed them a few times with different passwords to make sure.

I can't get into mysql at this point, to create the DB's pathfinder wants, stopping me from accessing the /setup/ directory to complete installation.

**Comment by porowns** [comment]
You probably need a new volume.

Direct support questions to our Discord please
