### ISSUE TITLE
Pathfinder on Docker for Ubuntu Pi

### ISSUE THREAD

**Issue by kamonzo** [porowns/pathfinder-docker#21]
When trying to set up Pathfinder via Docker on my Raspberry Pi I am running into an issue with mysql not finding an arm version in the manifests. Below is my error text. I imagine this is an easy fix I just don't know docker very well. Thanks!

ubuntu@ubuntu:~/pathfinder$ sudo docker-compose up -d
Pulling db (mysql:5.7)...
5.7: Pulling from library/mysql
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries

**Comment by porowns** [comment]
You'll have to find the MySQL image compatible with the Pi and specify it probably, if it even exists
