### ISSUE TITLE
possibility to build from source

### ISSUE THREAD

**Issue by ivveh** [porowns/pathfinder-docker#22]
Hey, would be great if you would add the code to build the dockers as well so that one can build it from source or with any custom modifications. As of writing pathfinder is v2.0.1 and the docker is v2.0.0.
Would be great if some info regarding the dockerfile could be put up on https://hub.docker.com/r/kryptedgaming/pathfinder

**Comment by porowns** [comment]
The dockerfile is in the repository, if you're interested you can just clone it down and do `docker build --build-arg VERSION=master .` (or similar command, on phone atm)

That's all we do when building our official image

**Comment by ivveh** [comment]
Oh darn, I totally missed that. Sorry and thanks! :)
