### ISSUE TITLE
ESI Setup

### ISSUE THREAD

**Issue by Achoo0-Adam** [porowns/pathfinder-docker#23]
Firstly fantastic Job on the Image. I apologies if this is more of a help request.

Just trying to test this locally (Localhost:8000) and run into the issue with the ESI? Im hoping to past this hurdle before trying to host it on aws/pws. Still quite "green" to this. Im sure my callback is incorrect on the dev ESI page.

`{"error":"invalid_request","error_description":"The callback URI doesn't match the value stored for this client`

My callback URI has been set to "http://localhost:8000/callback" and other things and I still get the above error. Hoping you have seen this and jumped this hurdle before. Thank you again for taking the time to create the docker image.

**Comment by ghost** [comment]
Set your callback URL in Eve Developers portal to http://localhost:8000/sso/callbackAuthorization
