### ISSUE TITLE
Errors in entrypoint.sh

### ISSUE THREAD

**Issue by vocino** [porowns/pathfinder-docker#26]
I can't see to get past this error during setup.

```
pathfinder_1  | Replacing settings
pathfinder_1  | /usr/local/bin/entrypoint.sh: line 27: [False: command not found
pathfinder_1  |  * Starting periodic command scheduler cron
pathfinder_1  |    ...done.
pathfinder_1  | Starting redis-server: redis-server.
```

Any advice?

**Comment by november781** [comment]
what does your .env file look like? Dont include stuff like `CCP_SSO_CLIENT_ID` and
`CCP_SSO_SECRET_KEY`

**Comment by vocino** [comment]
What should be filled out? The readme says to fill out the `.env`. I tried it using the default example `.env` with the same results.

**Comment by november781** [comment]
I'm mostly interested in what parameters you had set since line 27 of entrypoint.sh is ` if ["${UseRedis}" != "False"] ; then`.

If you have something odd in your .env I might be able to figure it out.

**Comment by vocino** [comment]
Yeah exactly. I was trying to debug by using a vanilla .env (from your template) as well as trying different value types for `UseRedis=`

**Comment by november781** [comment]
you could try removing that bit from the entrypoint.sh and rebuilding the container. I dont know what it is doing with your machine

I was able to get it up and running with a vanilla .env just now under windows with docker and have had this running happily on a VPS for amost a year now

**Comment by november781** [comment]
```
SETUP=False
VERSION=master
SERVER=PRODUCTION
SCHEME=http:\/\/
URL=pf.zapin.space
MYSQL_USER=root
MYSQL_PASSWORD={redacted}
CCP_SSO_CLIENT_ID={redacted}
CCP_SSO_SECRET_KEY={redacted}
CHARACTER=
CORPORATION=
ALLIANCE=99005130
UseRedis=True
CronWebUI=TRUE
NAME=SignalFinder
PrivateLIFETIME=60
PrivateMAX_COUNT=3
PrivateMAX_SHARED=100
PrivateMAX_SYSTEMS=300
PrivateLOG_ACTIVITY_ENABLED=1
PrivateLOG_HISTORY_ENABLED=1
PrivateSEND_HISTORY_SLACK_ENABLED=0
PrivateSEND_RALLY_SLACK_ENABLED=1
PrivateSEND_HISTORY_DISCORD_ENABLED=0
PrivateSEND_RALLY_DISCORD_ENABLED=1
PrivateSEND_RALLY_Mail_ENABLED=0
CorpLIFETIME=99999
CorpMAX_COUNT=5
CorpMAX_SHARED=4
CorpMAX_SYSTEMS=300
CorpLOG_ACTIVITY_ENABLED=1
CorpLOG_HISTORY_ENABLED=1
CorpSEND_HISTORY_SLACK_ENABLED=1
CorpSEND_RALLY_SLACK_ENABLED=1
CorpSEND_HISTORY_DISCORD_ENABLED=1
CorpSEND_RALLY_DISCORD_ENABLED=1
CorpSEND_RALLY_Mail_ENABLED=0
AddAdminChar=True
AdminCharID=2112813275
```

this is my .env file for reference

**Comment by vocino** [comment]
Not sure what's up. Tried this on a totally fresh setup with only `docker-compose.yml` and `.env` both templated from your files and got the same error. I have other docker-compose powered containers up and running on the same server. So frustrating, not sure what the issue is.

**Comment by vocino** [comment]
#29 looks like a fix. sorry, didn't dig into syntax but i think it's just a spacing issue.
